services:
  - mysql:5.5

variables:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_HOST: 'mysql'

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt update -qq && sudo apt dist-upgrade -y && sudo -E apt install -y build-essential libsqlite3-dev ruby ruby-dev bundler rubygems libmysqlclient-dev graphicsmagick inkscape mysql-client sphinxsearch
  - ruby -v
  - which ruby
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
image: leapcode/ruby
stages:
  - build
  - test
  - checks
bundle_audit:
  stage: checks
  allow_failure: true
  script: |
    sudo gem install bundler-audit
    bundle-audit update
    bundle-audit check
test:
  stage: test
  script: |
    bundle exec rake create_a_secret
    cp config/database.yml.example config/database.yml
    bundle exec rake db:create
    bundle exec rake db:schema:load
    bundle exec rake db:test:prepare
    RAILS_ENV=test bundle exec rake db:fixtures:load
    RAILS_ENV=test bundle exec rake ts:index ts:star
    bundle exec rake
    bundle exec rake test:pages:all

