before_script:
  - apt-get update -qq && apt-get install -y -qq build-essential ruby ruby-dev bundler rubygems
  - ruby -v
  - which ruby
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
stages:
  - checks
bundle_audit:
  stage: checks
  script: |
    gem install bundler-audit
    bundle-audit update
    bundle-audit check
