before_script:
  - sudo apt update -qq && sudo apt dist-upgrade -y && sudo apt install -y build-essential libsqlite3-dev ruby ruby-dev bundler rubygems libmysqlclient-dev
  - ruby -v
  - which ruby
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
image: leapcode/ruby
stages:
  - checks
bundle_audit:
  stage: checks
  script: |
    sudo gem install bundler-audit
    bundle-audit update
    bundle-audit check
